Algoritmo "calculos"

Var
largura,comprimento,perimetro,diagonal,area :real




Inicio

escreval("digite a largura do terreno")
leia(largura)
escreval("digite o comprimento do terreno")
leia(comprimento)


  area <- largura * comprimento
  perimetro <- 2 * largura + 2 * comprimento
  diagonal <- RaizQ( largura^2 + comprimento^2)
  




escreval(area)
escreval(perimetro)
escreval(diagonal:8:4)







Fimalgoritmo